# -*- coding: utf-8 -*-
"""Naive Bayesian Classifier. Ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Snt4PgXN9epwMx5GJD8NfL9np-ONLq6p
"""

import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.naive_bayes import CategoricalNB

# -------------------------------
# Step 1: Create the dataset
# -------------------------------

data = {
    'Outlook': ['Rainy','Rainy','Overcast','Sunny','Sunny','Sunny',
                'Overcast','Rainy','Rainy','Sunny','Rainy',
                'Overcast','Overcast','Sunny'],

    'Temp': ['Hot','Hot','Hot','Mild','Cool','Cool',
             'Cool','Mild','Cool','Mild','Mild',
             'Mild','Hot','Mild'],

    'Humidity': ['High','High','High','High','Normal','Normal',
                 'Normal','High','Normal','Normal','Normal',
                 'High','Normal','High'],

    'Windy': ['False','True','False','False','False','True',
              'True','False','False','False','True',
              'True','False','True'],

    'PlayGolf': ['No','No','Yes','Yes','Yes','No',
                 'Yes','No','Yes','Yes','Yes',
                 'Yes','Yes','No']
}

df = pd.DataFrame(data)

print("Dataset")
print(df)

# -------------------------------
# Step 2: Separate X and y
# -------------------------------

X = df[['Outlook','Temp','Humidity','Windy']]
y = df['PlayGolf']

# -------------------------------
# Step 3: Convert categories into numbers
# -------------------------------

encoder = OrdinalEncoder()

X_encoded = encoder.fit_transform(X)

print("\nEncoded Features")
print(X_encoded)

# -------------------------------
# Step 4: Train Naive Bayes
# -------------------------------

model = CategoricalNB()

model.fit(X_encoded, y)

# -------------------------------
# Step 5: Predict a new example
# -------------------------------

new_data = pd.DataFrame({
    'Outlook':['Sunny'],
    'Temp':['Cool'],
    'Humidity':['High'],
    'Windy':['True']
})

new_encoded = encoder.transform(new_data)

prediction = model.predict(new_encoded)

print("\nPrediction:", prediction[0])

# -------------------------------
# Step 6: Prediction Probability
# -------------------------------

probability = model.predict_proba(new_encoded)

print("\nProbability")
print("No :", probability[0][0])
print("Yes:", probability[0][1])